### ISSUE TITLE
Spurious warning when loading dictionary

### ISSUE THREAD

**Issue by jotbeel** [cgnieder/translations#10]
Attached is an MWE that shows translations issuing an, as it seems spurious warning:

> Package translations Warning: file `inner/faktury-polish.trsl' does not appear
to be a dictionary on input line 6.

This happens does happen when the dictionary is not in the same directory as the MWE.
The documentation does not say that this can not de done.

Best regards,
-- Jerzy Ludwichowski

[trsl.zip](https://github.com/cgnieder/translations/files/5152299/trsl.zip)

**Comment by cgnieder** [comment]
The manual says

> Loads a file named `<name>-<lang>.trsl` where `<lang>` corresponds to the lowercase name of the current language or base language as defined with `\DeclareLanguage`.

`inner/faktury` is not the `<name>` part of the file but partly a path name. The package assumes you put the dictionary where TeX looks for files, i.e., in the current folder or somewhere in the TeX tree, local or not.
In your case I'd just ignore the warning.
