### ISSUE TITLE
Translations can't be used in bookmarks

### ISSUE THREAD

**Issue by u-fischer** [cgnieder/translations#12]
From https://tex.stackexchange.com/q/587792/2388

acro hides translations in \unexpanded. This means that hyperref has no chance at all to get commands (and this includes unicode chars, accents and expandable commands) into the bookmarks:

~~~~
\documentclass[ngerman]{scrreprt}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{acro}
\usepackage{hyperref}

\def\blub{Abkürzung}

\DeclareAcroTranslation {list-name}
  {
    German     = Abkürzung-Ab\"urzungen-\blub 
  }  

\begin{document}

 \section{Abkürzung-Ab\"urzungen-\blub} 
 \printacronyms

\end{document}
~~~~

gives 

![image](https://user-images.githubusercontent.com/4047173/111506249-bd1ba500-8749-11eb-8543-ecba9e98ed5f.png)

**Comment by u-fischer** [comment]
> The bad boy actually is translations

well yes, but I didn't want to call it a bug that a package provides translation commands which return their content in a for hyperref unusable form. I was only sure that it is a bug in `acro` that it uses them in places (like a section title) where the code needs to work also in a PDF-string context.

**Comment by cgnieder** [comment]
I agree that it isn't a bug. However, quite a number of packages do use the translations in places where they could or do end up in PDF strings, e.g. `xsim`.

I need to look if I find why I introduced `\unexpanded` in the first place and will either drop it or will introduce two interfaces where one uses it and the other doesn't .
