### ISSUE TITLE
GetTranslation TeX error when using in sections 

### ISSUE THREAD

**Issue by nicocha30** [cgnieder/translations#13]
Hello,

When using `\GetTranslation` in section/chapter/... and no translation are available, it creates an undefined control sequence error in the document.

Examples : 

*Works :*

```tex
\documentclass{report}

\usepackage{babel}
\usepackage{translations}
\usepackage{hyperref}

\declaretranslation{French}{aaa}{}

\begin{document}
	
	\chapter{Chapter : \GetTranslation{aaa}}
	
\end{document}
```

*Doesn't works :* (Undefined control sequence. \end{document})

```tex
\documentclass{report}

\usepackage{babel}
\usepackage{translations}
\usepackage{hyperref}

%\declaretranslation{French}{aaa}{}

\begin{document}
	
	\chapter{Chapter : \GetTranslation{aaa}}
	
\end{document}
```

However, when using `GetTranslationWarn` instead of `GetTranslation`, the problem disappear.

Also, the problem does not occurs when using "hidden" sections, for example : `\section*{\GetTranslation{aaa}}`

Tested using `LuaHBTeX, Version 1.12.0 (TeX Live 2020)` and `pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)`.

Thanks,

Nicolas.

**Comment by cgnieder** [comment]
Thanks, fixed.
