### ISSUE TITLE
GetTranslation error in \DeclareNewTOC

### ISSUE THREAD

**Issue by krumeich** [cgnieder/translations#15]
In my document, I declare a custom list that shall have a localized name. It seems that \GetTranslation cannot be used in Koma Scripts \DeclareNewTOC. Consider the following snippet from a preamble (working mwe is attached, please rename file):

```
\DeclareTranslationFallback {listofapplicationnotes}{List of ST Application Notes}
\DeclareTranslation{English}{listofapplicationnotes}{List of ST Application Notes}
\DeclareTranslation{German} {listofapplicationnotes}{Liste der ST-Anwendungshinweise}

\DeclareNewTOC[listname={\GetTranslation{listofapplicationnotes}}]{appnote}
```

This results in the error:

```
./test.tex:14: Undefined control sequence.
<argument> @trnslt@language@\@trnslt@current@language 
                                           
l.14 ...anslation{listofapplicationnotes}}]{appnote}
                                                  
./test.tex:14: Undefined control sequence.
<argument> \@trnslt@current@language 
                          
l.14 ...anslation{listofapplicationnotes}}]{appnote}
```

Is this a bug/missing feature/user error?

Thanks for looking into this.

[gettranslations_mwe.txt](https://github.com/cgnieder/translations/files/6533423/gettranslations_mwe.txt)

**Comment by cgnieder** [comment]
The problem is that `\@trnslt@current@language` is not set up until begin document. Your example runs without errors if you do

```latex
\AtBeginDocument{\DeclareNewTOC[listname={\GetTranslation{listofapplicationnotes}}]{appnote}}
```
