### ISSUE TITLE
Generic hook 'file/after/translations-basic-dictionary-english.trsl' is deprecated.

### ISSUE THREAD

**Issue by PhelypeOleinik** [cgnieder/translations#18]
In the 2021-11-15 release the file hooks will be renamed to `file/<name>/after` rather than the current `file/after/<name>` so that all generic hooks follow the same naming pattern (see latex3/latex2e#648). Running the following MWE with `pdflatex-dev`:
```latex
\documentclass{article}
\usepackage{translations}
\begin{document}
\end{document}
```
prints this warning:
```none
LaTeX hooks Warning: Generic hook
(hooks)              'file/after/translations-basic-dictionary-english.trsl'
(hooks)              is deprecated.
(hooks)              Use hook
(hooks)              'file/translations-basic-dictionary-english.trsl/after'
(hooks)              instead.
```

The file hook rename was made so that the old names will still work for a while, but will eventually be deprecated and removed.  Thus `translations` will have to adapt eventually, but for now it should keep using the old names.

I suggest the update be done around February 2022, because then people have two months to update their LaTeX format before having `translations` updated, and because it is before the final TeX Live 2021 freeze, so systems that use frozen versions will not have the warning either.

The only change needed is:

```diff
diff --git a/./old/translations.sty b/./new/translations.sty
index f3fac4d..0b2a767 100644
--- a/./old/translations.sty
+++ b/./new/translations.sty
@@ -632,7 +632,7 @@
 % #1: name
 % #2: lang
 \newrobustcmd*\@trnslt@check@dictionary[2]{%
-  \AddToHook{file/after/#1-\@trnslt@language{#2}.trsl}
+  \AddToHook{file/#1-\@trnslt@language{#2}.trsl/after}
     {%
       \edef\@trnslt@tmpa{\@trnslt@language{#2}}%
       \ifcsdef{@trnslt@dictionary@#1@\@trnslt@tmpa}
```

**Comment by petiard** [comment]
Hello!

I think it's rather:

\AddToHook{file/#1-\@trnslt@language{#2}.trsl}

**Comment by PhelypeOleinik** [comment]
> `\AddToHook{file/#1-\@trnslt@language{#2}.trsl}`

Not really.  The hook is `file/<name>/after`. The hook without the "`/after`" bit does not exist, and the code stored there will never be used.

**Comment by petiard** [comment]
Yes, you're right.
Sorry for the noise

**Comment by PhelypeOleinik** [comment]
@petiard No worries :)

**Comment by schtandard** [comment]
> I suggest the update be done around February 2022, because then people have two months to update their LaTeX format before having `translations` updated, and because it is before the final TeX Live 2021 freeze, so systems that use frozen versions will not have the warning either.

I don't quite understand the reasoning here. Surely people who update their version of `translations` also update the kernel at the same time? Why wait until February?

**Comment by PhelypeOleinik** [comment]
@schtandard Not always.  There are quite a few cases (on stackexchange) of users that updated a package (for whatever reason) and didn't update LaTeX alongside.  On hindsight, maybe the suggestion was bad and it would be easier to tell those users to just update.
