### ISSUE TITLE
Non-translated words do not appear in non-latin environment

### ISSUE THREAD

**Issue by paternal** [cgnieder/translations#4]
I have written a package that uses `translations` to translate some words. But a user reported that when using it in hindi (a language that uses non-latin characters, for which I did not provide any translation), even the default translation is not displayed.

A minimal working example is attached (in txt, because github won't let me upload a tex file): [mwe-translations.txt](https://github.com/cgnieder/translations/files/926540/mwe-translations.txt).

The problem is that when `translations` does not find any translations for the given word, it dumps the key (composed as latin characters), and this is equivalent to mixing latin and non-latin characters, which does not work (for instance, in an hindi document, the word `foo` in the sentence `द्रिश्य foo द्रिश्य` is either ignored, or replaced by �����).

On solution is to provide as fallback the string `{\normalfontlatin KEY}`, but this only works with polyglossia; a similar solution exists for babel. Long story short, I came up with the following code, which does the job:

~~~tex
\makeatletter

\newcommand{\@latin}[1]{%
  % Try hard to display argument, even in an environment that uses non-latin characters.
  \ifdefined\normalfontlatin%
    {\normalfontlatin#1}% With polyglossia
  \else%
    {%
      \ifdefined\ensureascii%
        {\ensureascii{#1}}% With babel
      \else%
        {#1}% If neither polyglossia nor babel is loaded
      \fi%
    }%
  \fi%
}

\ProvideTranslationFallback{foo}{\@latin{foo}}

\makeatother
~~~

This seems to work, but:
1. If you have a cleaner solution, I would be pleased.
2. I think this issue should be addressed in `translations`, at least as a word in the documentation sayang *"Beware of non-latin languages…"*.

Regards,
-- Louis

**Comment by cgnieder** [comment]
I can reproduce the issue with *Noto Sans Devanagari* but when I use *Nakula* for example I get for 

```latex
\documentclass{article}

\usepackage{polyglossia}
\setmainlanguage{hindi}
\setmainfont[Script=Devanagari]{Nakula}

\RequirePackage{translations}
\DeclareTranslation{French}{dog}{chien}
%\DeclareTranslationFallback{dog}{{\normalfontlatin dog}}

\begin{document}

\GetTranslation{dog}

द्रिश्य

\end{document}
```

![translations](https://cloud.githubusercontent.com/assets/2248538/25121668/c34b75b0-2422-11e7-95ee-a9120bcb5b67.png)

both with XeLaTeX and LuaLaTeX…

So indeed this means that the translation and the fallback system works as it should… I'll add a hint to  look out for problems when language settings and font settings are intertwined like it is here…

**Comment by paternal** [comment]
Ok. This is a proof that I do not understand how non-latin fonts work in LaTeX… Sorry 😄

**Comment by cgnieder** [comment]
I know near to nothing about fonts ;)
