### ISSUE TITLE
\DeclareLanguageAlias introduces significant delay / scales badly  

### ISSUE THREAD

**Issue by Quoor8ee** [cgnieder/translations#5]
I noticed incredible slow-down of a TeX compile with the current TeXLive 2017 pretest (svn -r43990, translations-1.5b). It is a file with little complexity but numerous packages loaded, including `translations.sty` as a dependency of another package.

pdflatex stalls several seconds on including `translations.sty`, and later on also with `translations/translations-basic-dictionary-german.trsl`.
Total run needs 18.8(2) s. For comparison, TeXLive 2016 (Debian stretch, translations-1.4a) has finished after 6.73(3) s, so we are talking about a factor of three, at least on my modest ARM SBC (similar symptom on x86_64, though the absolute figures are not as impressive).
I wouldn't like this to be a TL17 show-stopper )-:

I tracked down the slowness to the list of `\DeclareLanguageAlias`: With `\ŧypeout`s inserted every ten lines, I can watch how the time to execute subsequent `\DeclareLanguageAlias` entries increases throughout the sequence, as if it were of quadratic (or even exponential) order in the number of loaded aliases.
For 1.4a this executions seem instantaneous, and the list itself hasn't changed a lot since then.

What happened to `\DeclareLanguageAlias`?

**Comment by cgnieder** [comment]
> What happened to `\DeclareLanguageAlias`?

Nothing. I didn't change the command since 2013/06/28 (v0.10)

**Comment by Quoor8ee** [comment]
Then this issue lies somewhere deeper.

MWE:

`time echo '\documentclass{minimal}\usepackage{translations}\begin{document}\LaTeX\end{document}' | pdflatex`
real    0m12,175s
user    0m12,120s
sys     0m0,050s

`time echo '\documentclass{minimal}\begin{document}\LaTeX\end{document}' | pdflatex`
real    0m0,676s
user    0m0,620s
sys     0m0,050s

**Comment by cgnieder** [comment]
Well, I don't have TL17 pretest and I'm not going to install it. As usual I will wait for the official release…

**Comment by Quoor8ee** [comment]
Hrm. The 1.5 branch has already been included in TeXLive 2016 for two months, see [https://www.tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/translations/translations.sty?r1=41384&r2=43392](url) . So anyone who installed or updated TL16 via the official repos since this march already got the new, slow code.

BTW, the delay amounts to about 1.2 seconds on a decent Xeon machine (0m1.349s vs. 0m0.133s)---which might be little enough to be overseen and ignored by end-users on more high-end hardware.

**Comment by cgnieder** [comment]
Your two MWEs on my system (2.5GHz quadcore and 7.7GiB RAM) with the latest TL16:

real    0m0.088s                                                                                                                                                                                
user    0m0.085s                                                                                                                                                                                
sys     0m0.004s

vs.

real    0m0.089s
user    0m0.086s
sys     0m0.004s

**Comment by Quoor8ee** [comment]
What version of translations.sty are you using?
Some statistics why I find this increasingly puzzling: I have tested the MWEs on quite any hardware I could get my fingers on, and I NEVER saw the ratio of run times dropping below 2.5!

The tests were on 12 different machines (x86_64 AMD+Intel, armv7h, aarch64, powerpc; from sluggish smartphone-alikes to 64-core 19" rackservers) with 6 OSes (Debian, Archlinux, Gentoo, FreeBSD, LinuxMint, Ubuntu) and 7 different TeXLive sources (SVN, web and direct DVD installs (local access or via NFS), as well as provided by OS package management), 18 largely independent TeX environments in total.

There is some variance, but there is a definite trend:
translations-1.2a (TL2014+2015) slows down the MWE by a factor of about 3.
translations-1.5a (in the original TL2016) creates an average slowdown of 9 (the `best' being as little as 4).
The system for which I reported this initially (translations-1.5c, TL16 updates + TL17 svn) is by far the worst (factor >18), but probably a runaway due to immature compiler optimisation on AArch64.
A systematic increase of absolute times is visible if the TeX tree is accessed via NFS, but in terms of the ratios, they are in shape with local HDD access.

That's the data, sorry. So either my typing is profoundly cursed, or we are talking about different things.

**Comment by cgnieder** [comment]
I'm afraid I cannot help. `translations` has not significantly changed from v1.2 to 1.5. In fact it lost dependencies from `cnltx-base` with v1.5 so if anything I would expect it now to be faster than with older versions.

> What version of translations.sty are you using?

As I said I used the latest TL16 which has v1.5c (2017-05-06).

Did you try to check what happens if you load packages with *a lot* more code than `translations`, e.g. `expl3`?

**Comment by Quoor8ee** [comment]
`time echo '\documentclass{minimal}\usepackage{translations}\begin{document}\LaTeX\end{document}' | pdflatex`
real    0m12,377s
user    0m12,280s
sys     0m0,090s

`time echo '\documentclass{minimal}\usepackage{scrlfile,etoolbox}\begin{document}\LaTeX\end{document}' | pdflatex` (the dependencies of translations.sty)
real    0m0,719s
user    0m0,630s
sys     0m0,080s

`time echo '\documentclass{minimal}\usepackage{scrlfile,etoolbox,expl3}\begin{document}\LaTeX\end{document}' | pdflatex`
real    0m1,182s
user    0m1,080s
sys     0m0,090s

So we (well, at least me) can be sure that the complexity arises from logic inside `translations.sty`. For I have patched 
```--- translations.sty.orig       2017-05-15 21:54:51.808470825 +0200
+++ translations.sty    2017-05-15 21:54:30.297827009 +0200
@@ -239,6 +239,7 @@
 % #1: alias
 % #2: language
 \newrobustcmd*\DeclareLanguageAlias[2]{%
+  \immediate\write18{date +\%s\%N}
   \@trnslt@declare@languagealias{#1}{#2}}
 \@onlypreamble\DeclareLanguageAlias
```

to print out the progress in processing the language aliases, and I observe strikingly smooth exponential growth of `\DeclareLanguageAlias` execution time, doubling each and every 97 calls (112 on high-end hardware). This seems like some nasty detail of how TeX handles lists (and is probably not restricted to `translations` alone), but this makes me even more unsure about how to explain your timing figures...

**Comment by cgnieder** [comment]
The increase you observe very likely comes from the fact that `\DeclareLanguageAlias` adds the new alias to a list after checking if it is already in there…

```latex
\@trnslt@ifinlist{#1}\@trnslt@aliases@single{}{...}
```

while earlier versions used

```latex
\ifinlist{#1}\@trnslt@aliases@single
```

I am not sure the check is even necessary. This should do quite as well and will probably solve your speed issues:

```latex
\newrobustcmd*\@trnslt@declare@languagealias[2]{%
  \@trnslt@if@language{#2}
    {}{%
      \@trnslt@warn@unknown@lang{#2}%
      \@trnslt@declare@language{#2}%
    }%
  \csletcs{@trnslt@language@#1}{@trnslt@language@#2}%
  \@trnslt@if@dialect{#2}
    {\csletcs{@trnslt@dialect@#1}{@trnslt@dialect@#2}}
    {}%
  \ifcsdef{@trnslt@alias@#1}
    {}
    {%
      \csdef{@trnslt@alias@#1}{#2}%
      \listeadd\@trnslt@aliases@pair{{#1}{#2}}%
      \listeadd\@trnslt@aliases@single{#1}%
    }%
}
```

The same probably happens with `\NewDictTranslation` or more precisly with `\@trnslt@check@dictionary@entry` which performs a similar check. I can probably change that as well…

**Comment by Quoor8ee** [comment]
Many thanks! That does the trick!
real    0m3,903s
user    0m3,860s
sys     0m0,040s

At least most of it. But yes, the ```\NewDictTranslation``` has been slowing down loading ```translations-basic-dictionary-english.trsl``` in a similar fashion. Naïvely replacing `\@trnslt@ifinlistcs` by `\ifcsdef` within `\@trnslt@check@dictionary@entry` makes the compile time implode to mere 0.63 seconds (-8 .

So if you feel comfortable with replacing `\@trnslt@ifinlist` by `\ifcsdef` (within `\@trnslt@declare@languagealias`; for `\@trnslt@check@dictionary@entry` the same trick at least runs w/o errors, but you are the expert on your code), I'd be perfectly happy!

**Comment by cgnieder** [comment]
Please try commit https://github.com/cgnieder/translations/commit/5f040275f864db0d2a6f216d1c269818f2f10221

**Comment by Quoor8ee** [comment]
`time echo '\documentclass{minimal}\usepackage{translations}\begin{document}\LaTeX\end{document}' | pdflatex`
real    0m0,873s
user    0m0,790s
sys     0m0,080s

Great! Thanks!
