### ISSUE TITLE
\SaveTranslation(For) doesn't use Fallbacks

### ISSUE THREAD

**Issue by Vidabe** [cgnieder/translations#6]
It seems that `\SaveTranslation(For)` doesn't use the translation-fallback leaving the command
empty if no translation is defined.

```tex
\documentclass{article}
\usepackage{translations}

\NewTranslationFallback{Test}{A Test}
\begin{document}

\SaveTranslation \Test {Test}
\Test

\end{document}
```

It is a bit strange as it works perfectly with `\GetTranslation`

**Comment by cgnieder** [comment]
Thanks for the report!

**Comment by Vidabe** [comment]
Thanks for the quick fix!

Although now `\SaveTranslation(For)` fully expand its `<translation>` which it didn't do before
(should I open a new Issue about it?).

**Comment by cgnieder** [comment]
But why shouldn't it do that? IMHO that should be the expected behaviour.

One could argue, though, that `\@trnslt@checkandget@translation@for` should return the retrieved values in `\unexpanded`…

**Comment by Vidabe** [comment]
I would argue that one uses `\SaveTranslation` *because* the translation shouldn't be expanded,
but only fetched for further processing (or else one would simply use `\edef\CMD{\GetTranslation{key}}`). 

Furthermore, if (like me) someone is coming from the "translator" package this would be the expected behavior (as `\translatelet` only fetches the translation, but does not expand it).

**Comment by cgnieder** [comment]
The same argument goes for the non-expanding case: `\def\CMD{\GetTranslation{key}}`. I certainly originally *intended* the commands to save the expanded version. It's also how the manual describes the commands… From my point of view the previous behaviour was buggy.

**Comment by Vidabe** [comment]
Ah ok, I just wasn't sure which behavior was intended.
