### ISSUE TITLE
Language detection is based upon the not recommended babel's \languagename

### ISSUE THREAD

**Issue by dbitouze** [cgnieder/translations#7]
AFAICS, `translations` language detection is based upon `babel`'s `\languagename`:

``` latex
\def\@trnslt@current@language{\languagename}%
```

But `babel`'s documentation (page 27) warns about possible deficiency of `\languagename`:

> The control sequence `\languagename` contains the name of the current language.
**WARNING** Due to some internal inconsistencies in catcodes, it should _not_ be used
to test its value. Use `iflang`, by Heiko Oberdiek.

**Comment by cgnieder** [comment]
`translations` turns the language name into a series of category code 12 characters before testing it. So far there hasn't been any problem that I am aware of…

**Comment by dbitouze** [comment]
I didn't detect any problem either :) It was just to draw your attention.
