### ISSUE TITLE
PrintDictionaryFor not working

### ISSUE THREAD

**Issue by kellertuer** [cgnieder/translations#8]
In the documentation it seems, that `\PrintDictionaryFor` is not working and Table 1 is empty. I get the same with my local own dictionary when adapting your code accordingly. Can you check why this seem to be broken?

**Comment by cgnieder** [comment]
I need to check what the problem in the manual is… but the command is working for me:

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[ngerman,english]{babel}
\usepackage{translations,longtable,booktabs}

\newcommand*\translations{\texttt{translations}}

\begin{document}

\begin{longtable}{ll}
    \caption{All entries of \translations' basic dictionary in German.\label{tab:dict}} \\
    \toprule
    \rmfamily\bfseries key & \bfseries translation \\
    \midrule
  \endfirsthead
    \toprule
    \rmfamily\bfseries key & \bfseries translation \\
    \midrule
  \endhead
    \bottomrule
  \endlastfoot
    \midrule
    & \hfill\emph{continues} \\
  \endfoot
  \PrintDictionaryFor{German}{translations-basic-dictionary}{\ttfamily}{&}{\\}
\end{longtable}

\end{document}
```

**Comment by kellertuer** [comment]
Ah compiling twice makes it work, too on my side – so what was the problem with the manual? Despite the manual not displaying the German dictionary, this can be closed.

**Comment by cgnieder** [comment]
I couldn't detect the *real* problem but I slightly changed how dictionaries are loaded and now it is fixed, anyway.

**Comment by kellertuer** [comment]
Cool, well it works on my side (again) as mentioned, I can not really reproduce what was wrong.

But: Thanks for providing this nice package. It helps when providing multilang documents.
