### ISSUE TITLE
v1.8a breaks \LoadDictionary{}

### ISSUE THREAD

**Issue by Quoor8ee** [cgnieder/translations#9]
I'm on a regular, current TeXLive (installed today) on Linux. Current TL downstream `translations.sty` breaks when `\LoadDictionary` is used. I found it since it broke Louis Paternault's `thalie.sty` package that happens to be the only TL-distributed CTAN package to use straight `\LoadDirectory` (but who knows how many custom packages depend on it as well).

MWE:
```
\documentclass{minimal}
\usepackage{translations}\LoadDictionary{mwe}
\begin{document}
\end{document}
```
runs well  with v1.8 as of [TL -r53962, 2020-02-28](https://www.tug.org/svn/texlive?view=revision&revision=53962), but dies with v1.8a as of [TL -r54889, 2020-04-26](https://www.tug.org/svn/texlive?view=revision&revision=54899) with
```
! Undefined control sequence.
<argument> ...@language@\@trnslt@current@language 
                                                  
l.34 \LoadDictionary{thalie}
                            
? x
No pages of output.
```
 I haven't dug very deep into this yet, but reverting [the changeset](https://www.tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/translations/translations.sty?r1=53962&r2=54899) at least makes the MWE run again, without clue about logical correctness of what happens. The `thalie` package hasn't changed within the last three years.

**Comment by cgnieder** [comment]
Thanks, fixed.
